run:
  tests: true

linters-settings:
  gci:
  # Section configuration to compare against.
  # Section names are case-insensitive and may contain parameters in ().
  # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`,
  # If `custom-order` is `true`, it follows the order of `sections` option.
  # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
      - prefix(github.com/derticom/) # Custom section: groups all imports with the specified Prefix.
      - default #
    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    custom-order: true
  funlen:
    lines: 150
    statements: 80

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace